"""moonwalk-nanopay.

A Python SDK for the MoonWalk USDC payment channel on Arc mainnet. Sign vouchers
off-chain, settle in batches. The payer signs everything and sends no
transaction. Whoever wants the money on chain submits. On Arc they pay that gas
in the same USDC they are collecting.
"""

from __future__ import annotations

from .addresses import (
    ARC_CHAIN_ID,
    ARC_EXPLORER_URL,
    ARC_RPC_URL,
    CLOSE_TYPE_STRING,
    DEFAULT_DEPOSIT_TTL_SECONDS,
    DEFAULT_VOUCHER_TTL_SECONDS,
    MAINNET_ADDRESSES,
    NANO_CHANNEL_ADDRESS,
    NANO_CHANNEL_DOMAIN_NAME,
    NANO_CHANNEL_DOMAIN_VERSION,
    ONCHAIN_OPEN_TYPEHASH,
    ONCHAIN_VOUCHER_TYPEHASH,
    OPEN_TYPE_STRING,
    RECEIVE_WITH_AUTHORIZATION_TYPE_STRING,
    SERVICE_REGISTRY_ADDRESS,
    SPEND_GUARD_ADDRESS,
    USDC_ADDRESS,
    USDC_DECIMALS,
    USDC_DOMAIN_NAME,
    USDC_DOMAIN_VERSION,
    VOUCHER_TYPE_STRING,
    ZERO_ADDRESS,
    Addresses,
    address_url,
    tx_url,
)
from .client import NanopayClient, load_abi
from .ids import SUBJECT_PREFIX, channel_id, subject_id, subject_label
from .signing import (
    build_authorization,
    close_digest,
    open_digest,
    random_nonce,
    recover_voucher,
    sign_close,
    sign_open,
    sign_receive_with_authorization,
    sign_voucher,
    voucher_digest,
)
from .types import (
    Authorization,
    Cap,
    ChannelState,
    DomainConfig,
    OpenChannelResult,
    PreparedTransaction,
    SentTx,
    SignedVoucher,
    Usage,
    Voucher,
)

__version__ = "0.1.0"

__all__ = [
    "ARC_CHAIN_ID",
    "ARC_EXPLORER_URL",
    "ARC_RPC_URL",
    "CLOSE_TYPE_STRING",
    "DEFAULT_DEPOSIT_TTL_SECONDS",
    "DEFAULT_VOUCHER_TTL_SECONDS",
    "MAINNET_ADDRESSES",
    "NANO_CHANNEL_ADDRESS",
    "NANO_CHANNEL_DOMAIN_NAME",
    "NANO_CHANNEL_DOMAIN_VERSION",
    "ONCHAIN_OPEN_TYPEHASH",
    "ONCHAIN_VOUCHER_TYPEHASH",
    "OPEN_TYPE_STRING",
    "RECEIVE_WITH_AUTHORIZATION_TYPE_STRING",
    "SERVICE_REGISTRY_ADDRESS",
    "SPEND_GUARD_ADDRESS",
    "SUBJECT_PREFIX",
    "USDC_ADDRESS",
    "USDC_DECIMALS",
    "USDC_DOMAIN_NAME",
    "USDC_DOMAIN_VERSION",
    "VOUCHER_TYPE_STRING",
    "ZERO_ADDRESS",
    "Addresses",
    "Authorization",
    "Cap",
    "ChannelState",
    "DomainConfig",
    "NanopayClient",
    "OpenChannelResult",
    "PreparedTransaction",
    "SentTx",
    "SignedVoucher",
    "Usage",
    "Voucher",
    "__version__",
    "address_url",
    "build_authorization",
    "channel_id",
    "close_digest",
    "load_abi",
    "open_digest",
    "random_nonce",
    "recover_voucher",
    "sign_close",
    "sign_open",
    "sign_receive_with_authorization",
    "sign_voucher",
    "subject_id",
    "subject_label",
    "tx_url",
    "voucher_digest",
]
